create table public.employers (
  id bigint generated by default as identity primary key,
  assigned_view text not null check (assigned_view in ('AO1', 'AO2', 'AO3')),
  employer_number text not null,
  employer_name text not null,
  address text,
  principal numeric(12, 2) not null default 0,
  penalty numeric(12, 2) not null default 0,
  interest numeric(12, 2) not null default 0,
  total_amount numeric(12, 2) not null default 0,
  billing_date date,
  coverage_date date,
  soa_date date,
  status text not null check (status in ('Settled', 'Unsettled', 'Registed', 'Not Yet Registered')),
  created_at timestamptz not null default now()
);

create index employers_assigned_view_idx on public.employers (assigned_view);

alter table public.employers enable row level security;