create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  username text not null unique,
  full_name text,
  password_hash text not null,
  role text not null check (role in ('Super Admin', 'Admin', 'Assistant Officer 1', 'Assistant Officer 2', 'Assistant Officer 3', 'User')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.employers (
  id bigint generated by default as identity primary key,
  assigned_view text not null check (assigned_view in ('AO1', 'AO2', 'AO3')),
  employer_number text not null,
  employer_name text not null,
  address text,
  principal numeric(12, 2) not null default 0,
  penalty numeric(12, 2) not null default 0,
  interest numeric(12, 2) not null default 0,
  total_amount numeric(12, 2) not null default 0,
  billing_date date,
  coverage_date date,
  soa_date date,
  status text not null check (status in ('Settled', 'Unsettled', 'Registed', 'Not Yet Registered')),
  created_at timestamptz not null default now()
);

create index employers_assigned_view_idx on public.employers (assigned_view);
create index users_role_idx on public.users (role);
create index users_username_idx on public.users (username);

alter table public.users enable row level security;
alter table public.employers enable row level security;

create policy "Users can read their own account" on public.users
  for select using (false);

create policy "Admins can read all users" on public.users
  for select using (false);

create trigger set_users_updated_at
before update on public.users
for each row
execute procedure public.set_updated_at();